//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo {
    
    
    public partial class feedback {
        
        protected System.Web.UI.WebControls.Content Content1;
        
        protected System.Web.UI.WebControls.Content Content3;
        
        protected HuaYimo.uc.uc_menu uc_menu;
        
        protected System.Web.UI.WebControls.Content Content2;
        
        protected HuaYimo.uc.uc_breadcrumb uc_breadcrumb;
        
        protected System.Web.UI.WebControls.Label lbWebName;
        
        protected System.Web.UI.WebControls.Label lbWeiXin;
        
        protected System.Web.UI.WebControls.Label lbQQ;
        
        protected System.Web.UI.WebControls.Label lbAddress;
        
        protected System.Web.UI.WebControls.Label lbTelPhone;
        
        protected System.Web.UI.WebControls.Label lbMobilPhone;
        
        protected System.Web.UI.WebControls.Label lbFax;
        
        protected System.Web.UI.HtmlControls.HtmlInputText tbusername;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        
        protected System.Web.UI.HtmlControls.HtmlInputText tbphone;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        
        protected System.Web.UI.HtmlControls.HtmlInputText tbemail;
        
        protected System.Web.UI.HtmlControls.HtmlInputText tbcompany;
        
        protected System.Web.UI.HtmlControls.HtmlInputText tbaddress;
        
        protected System.Web.UI.HtmlControls.HtmlInputText tbtitle;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        protected System.Web.UI.HtmlControls.HtmlTextArea tbcontent;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
        
        protected System.Web.UI.WebControls.Button btSub;
        
        protected System.Web.UI.WebControls.ValidationSummary vs;
    }
}
