//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo {
    
    
    public partial class news_pic {
        
        protected System.Web.UI.WebControls.Content Content1;
        
        protected System.Web.UI.WebControls.Content Content3;
        
        protected HuaYimo.uc.uc_menu uc_menu;
        
        protected System.Web.UI.WebControls.Content Content2;
        
        protected HuaYimo.uc.uc_breadcrumb uc_breadcrumb;
        
        protected HuaYimo.uc.uc_leftmenu uc_leftmenu;
        
        protected System.Web.UI.WebControls.Repeater rpNewslist;
        
        protected System.Web.UI.WebControls.Label lbpagenow;
        
        protected System.Web.UI.WebControls.Label lbpagetotal;
        
        protected System.Web.UI.WebControls.Label lbnumber;
        
        protected System.Web.UI.WebControls.Label lbnumbertotal;
        
        protected System.Web.UI.WebControls.HyperLink lpfirst;
        
        protected System.Web.UI.WebControls.HyperLink lpprev;
        
        protected System.Web.UI.WebControls.Label lbGid;
        
        protected System.Web.UI.WebControls.HyperLink lpnext;
        
        protected System.Web.UI.WebControls.HyperLink lplast;
        
        protected System.Web.UI.WebControls.HyperLink lpfirst2;
        
        protected System.Web.UI.WebControls.HyperLink lpprev2;
        
        protected System.Web.UI.WebControls.Label lbGid2;
        
        protected System.Web.UI.WebControls.HyperLink lpnext2;
        
        protected System.Web.UI.WebControls.HyperLink lplast2;
    }
}
