//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo {
	
	
	public partial class page404 {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected HuaYimo.uc.uc_menu uc_menu;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected HuaYimo.uc.uc_breadcrumb uc_breadcrumb;
	}
}
