//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.uc {
	
	
	public partial class uc_footer {
		
		protected System.Web.UI.WebControls.Label lbWebName;
		
		protected System.Web.UI.WebControls.Label lbAddress;
		
		protected System.Web.UI.WebControls.Label lbMobilePhone;
		
		protected System.Web.UI.WebControls.Label lbTePhone;
		
		protected System.Web.UI.WebControls.Label lbFax;
		
		protected System.Web.UI.WebControls.Repeater rpZD;
		
		protected System.Web.UI.WebControls.Repeater rpLink;
	}
}
