//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class admin_add {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList ddlrole;
		
		protected System.Web.UI.WebControls.TextBox tbName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox tbTruename;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.Panel panEdit;
		
		protected System.Web.UI.WebControls.TextBox tbPass;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox tbPass2;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
		
		protected System.Web.UI.WebControls.Panel panReset;
		
		protected System.Web.UI.WebControls.TextBox tbRestPass;
		
		protected System.Web.UI.WebControls.RadioButtonList rbFlag;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton Submit1;
		
		protected System.Web.UI.WebControls.Button btEdit;
	}
}
