//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class admin_manage {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.CheckBox chkAll;
		
		protected System.Web.UI.WebControls.Repeater rtAdmin;
		
		protected System.Web.UI.WebControls.Button btDel;
	}
}
