//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class advInfo_add {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox tbtitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox tbimgUrl;
		
		protected System.Web.UI.WebControls.TextBox tbimgLink;
		
		protected System.Web.UI.WebControls.TextBox tbFlyImageWidth;
		
		protected System.Web.UI.WebControls.TextBox tbFlyImageHeight;
		
		protected System.Web.UI.WebControls.TextBox tbAddTime;
		
		protected System.Web.UI.WebControls.RadioButtonList rbFlag;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton Submit1;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton sbEdit;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton btBack;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden hdUrl;
	}
}
