//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.HtmlControls.HtmlInputControl txtUserName;
        
        protected System.Web.UI.HtmlControls.HtmlInputText txtPassWord;
        
        protected System.Web.UI.WebControls.ImageButton imgBut;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
    }
}
