//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class link_add {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox tbtitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox tburl;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.Panel panEdit;
		
		protected System.Web.UI.WebControls.DropDownList ddltype;
		
		protected System.Web.UI.WebControls.TextBox tbsort;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.RadioButtonList rbFlag;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton Submit1;
		
		protected System.Web.UI.WebControls.Button btEdit;
	}
}
