//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class main_left {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.WebControls.Literal ltName;
		
		protected System.Web.UI.WebControls.Repeater rpMenu;
		
		protected System.Web.UI.WebControls.Repeater rpIntro;
	}
}
