//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class news_type {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HyperLink hlBack;
		
		protected System.Web.UI.WebControls.TextBox tbTitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox tbSord;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
		
		protected System.Web.UI.HtmlControls.HtmlTableRow trIssimple;
		
		protected System.Web.UI.WebControls.RadioButtonList rbIssimple;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton Submit1;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton sbEdit;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton btBack;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden hdUrl;
		
		protected System.Web.UI.WebControls.Repeater rpNewsDefault;
		
		protected System.Web.UI.WebControls.GridView gvMain;
		
		protected System.Web.UI.WebControls.CheckBox chkAll;
		
		protected System.Web.UI.WebControls.Button btDel;
	}
}
