//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class news_add {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbTitle;
		
		protected System.Web.UI.WebControls.DropDownList ddlptype;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator2;
		
		protected System.Web.UI.WebControls.DropDownList ddlType;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
		
		protected System.Web.UI.WebControls.TextBox tbTitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox tbTitle2;
		
		protected System.Web.UI.WebControls.TextBox tbAuthor;
		
		protected System.Web.UI.WebControls.TextBox tbSource;
		
		protected System.Web.UI.WebControls.TextBox txtFull;
		
		protected System.Web.UI.WebControls.FileUpload upFile;
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.Button btDelImg;
		
		protected System.Web.UI.WebControls.FileUpload upFile1;
		
		protected System.Web.UI.WebControls.Button btDelFile;
		
		protected System.Web.UI.WebControls.TextBox tbfile;
		
		protected System.Web.UI.HtmlControls.HtmlTableRow trdownload1;
		
		protected System.Web.UI.WebControls.TextBox tburl;
		
		protected System.Web.UI.HtmlControls.HtmlTableRow trdownload2;
		
		protected System.Web.UI.WebControls.RadioButtonList rbisdiredict;
		
		protected System.Web.UI.WebControls.TextBox tbTime;
		
		protected System.Web.UI.WebControls.RadioButtonList rbComm;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton Submit1;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton sbEdit;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton btBack;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden hdUrl;
	}
}
