//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class news_audit {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.CheckBox chkAll;
		
		protected System.Web.UI.WebControls.Repeater rtNews;
		
		protected System.Web.UI.WebControls.Label lbpagenow;
		
		protected System.Web.UI.WebControls.Label lbpagetotal;
		
		protected System.Web.UI.WebControls.Label lbnumber;
		
		protected System.Web.UI.WebControls.Label lbnumbertotal;
		
		protected System.Web.UI.WebControls.HyperLink lpfirst;
		
		protected System.Web.UI.WebControls.HyperLink lpprev;
		
		protected System.Web.UI.WebControls.Label lbGid;
		
		protected System.Web.UI.WebControls.HyperLink lpnext;
		
		protected System.Web.UI.WebControls.HyperLink lplast;
		
		protected System.Web.UI.WebControls.Button btDel;
		
		protected System.Web.UI.WebControls.Button btAudit;
	}
}
