//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
	
	
	public partial class role_rank {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbrolename;
		
		protected System.Web.UI.WebControls.CheckBox chkAll;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox1;
		
		protected System.Web.UI.WebControls.Label lbmodule1;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule1;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox2;
		
		protected System.Web.UI.WebControls.Label lbmodule2;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule2;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox3;
		
		protected System.Web.UI.WebControls.Label lbmodule3;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule3;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox4;
		
		protected System.Web.UI.WebControls.Label lbmodule4;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule4;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox5;
		
		protected System.Web.UI.WebControls.Label lbmodule5;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule5;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox6;
		
		protected System.Web.UI.WebControls.Label lbmodule6;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule6;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox7;
		
		protected System.Web.UI.WebControls.Label lbmodule7;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule7;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox8;
		
		protected System.Web.UI.WebControls.Label lbmodule8;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule8;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox9;
		
		protected System.Web.UI.WebControls.Label lbmodule9;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule9;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox10;
		
		protected System.Web.UI.WebControls.Label lbmodule10;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule10;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox11;
		
		protected System.Web.UI.WebControls.Label lbmodule11;
		
		protected System.Web.UI.WebControls.CheckBoxList cblmodule11;
		
		protected System.Web.UI.WebControls.Button btSub;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden hdback;
	}
}
