//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaYimo.admin {
    
    
    public partial class webSite_set {
        
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.TextBox tsName;
        
        protected System.Web.UI.WebControls.TextBox tsTitle;
        
        protected System.Web.UI.WebControls.TextBox tsSiteUrl;
        
        protected System.Web.UI.WebControls.TextBox tsSiteLogo;
        
        protected System.Web.UI.WebControls.TextBox tsAddress;
        
        protected System.Web.UI.WebControls.TextBox tsFax;
        
        protected System.Web.UI.WebControls.TextBox tsTel;
        
        protected System.Web.UI.WebControls.TextBox tsPhone;
        
        protected System.Web.UI.WebControls.TextBox tsWeiXin;
        
        protected System.Web.UI.WebControls.TextBox tsQQ;
        
        protected System.Web.UI.WebControls.TextBox tbContent;
        
        protected System.Web.UI.WebControls.TextBox tsDescription;
        
        protected System.Web.UI.WebControls.TextBox tsKeywords;
        
        protected System.Web.UI.WebControls.TextBox tbsCount;
        
        protected System.Web.UI.WebControls.RegularExpressionValidator rev1;
        
        protected System.Web.UI.WebControls.Button btSub;
    }
}
